language: python

python: "3.5"

sudo: false

services:
    - mongodb
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-2.x
    packages:
    - mongodb-org-server
    - elasticsearch
    - libxmlsec1-dev

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -t stable elasticsearch
    - sudo service elasticsearch restart
    - nvm install node
    - nvm use node
    - node --version
    - npm install -g npm@latest
    - npm install -g grunt-cli

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install && cd ..

script:
    - cd server && flake8 && pytest && behave && cd ..
    - cd client && grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..
