language: python

python: "3.5"

sudo: false

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - libxmlsec1-dev

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - nvm install node
    - nvm use node
    - node --version
    - npm install -g npm@latest
    - npm install -g grunt-cli
    - pip install requests

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install && cd ..

script:
    - cd server && flake8 && cd ..
    - cd client && grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..
